# Generated by Django 3.2.18 on 2023-05-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0003_auto_20230518_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selectedGenres',
            field=models.ManyToManyField(blank=True, to='movies.Genre'),
        ),
    ]
